### ISSUE TITLE
Titre de l'article non rapporté sur Europresse

### ISSUE THREAD

**Issue by SOY75** [Write/ophirofox-userscript#1]
Bonjour
Le plugin fonctionne partiellement, j'ai bien le bouton "Lire sur Europresse", il me redirige vers bien vers Europresse (const universityName = "Pas d'intermédiaire" pour ma part) mais je me retrouve à devoir copier coller le titre de l'article manuellement car celui-ci n'apparait pas dans la barre de recherche.

J'ai essayé plusieurs versions, et de désactiver adguard mais sans succès, je suis sur la dernière version de safari avec Tampermonkey.

Comment puis-je vous aider à régler ce problème ? 

Merci

**Comment by Write** [comment]
Bonjour,

Je n'utilise pas Tampermonkey mais [Userscripts](https://apps.apple.com/us/app/userscripts/id1463298887).

Cependant, j'avais acheté  Tampermonkey, donc j'ai pu tester sur LeMonde et la complétion automatique a l'air de fonctionner.

Je ne peux pas utiliser l'option "pas d'intermédiaire" mais je ne pense pas que le problème vienne de là.

Il faudrait voir des erreurs éventuelles dans la console. Sur Safari, il me semble qu'il faut d'abord activer le mode dév dans l'onglet "Avancés" et tout en bas "Afficher les fonctionnalités pour les développeurs web", tu pourras en suite appuyer sur ALTR+CTRL+i pour afficher celle-ci. Ouvre là avant de cliquer sur "Lire sur europresse".

Sur quel(s) site(s) cela ne marche pas ?

**Comment by SOY75** [comment]
Bonjour
J'ai testé sur LeMonde, LeFigaro et courrier international.
J'ai regardé dans le mode dev mais je n'ai rien trouvé à première vue.
Est-ce que tu peux me partager ton mail ? Je vais t'envoyer mes identifiants Europresse si ça te convient, ça sera plus facile comme ça.

Merci en tout cas

**Comment by Write** [comment]
Ah ouai vraiment bizarre que ça ne marche nulle part...
Tu as quelle version de macOS ? Vu que la version de Safari est liée à la version de l'OS.

github@schroed.fr

**Comment by Write** [comment]
Je ne peux que te conseiller de voir si ça fait la même chose sur l'extension Userscripts.
Bien sûr, bien désactiver l'userscript sur Tampermonkey avant.

**Comment by SOY75** [comment]
Pas de soucis, je teste dans la journée et je te dis.

**Comment by Write** [comment]
Bon, on a le même en plus, sauf que je suis en 14.4 et donc Safari 17.4 mais bon, je ne pense pas que ça ait un rapport.

**Comment by Write** [comment]
Du nouveau ? 

Tu peux m'envoyer les logins ici si jamais : [github@schroed.fr](mailto:github@schroed.fr)

**Comment by Write** [comment]
Ok,
avec les logins, je peux te confirmer que j'arrive à reproduire le bug, en fait la page de recherche n'est pas la même quand on se login direct, je n'avais donc pas pu le voir.

**Comment by Write** [comment]
Je viens de fix le bug à la main, sûrement un problème d'index, mais plus facilement réglé en ajoutant juste l'URL manquante à la main :-) 

Par contre, il reste un bug, mais qui est aussi présent dans l'extension Ophirofox, quand on vient de regarder un article la recherche est sauvée, et quand on reclique sur un autre "Lire sur Europresse", c'est l'ancienne recherche qui apparaît immédiatement, et il faut juste recliquer une fois sur la barre en haut "Recherche express" pour que la nouvelle recherche se fasse... hmm.

**Comment by SOY75** [comment]
Merci infiniment pour ta réactivité. Effectivement j'ai déjà eu ce bug, je le signalerai là bas.
